import javax.swing.JOptionPane;
import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 * The EditMenuHandler class handles the search functionality.
 * It implements the ActionListener interface to handle actions when Search is clicked in the GUI.
 * @author Rodba Khondoker
 */
class EditMenuHandler implements ActionListener {
    private Date212GUI dateGUI;

    /**
     * Constructs an EditMenuHandler with a reference to the Date212GUI.
     *
     * @param dateGUI The Date212GUI instance.
     */
    public EditMenuHandler(Date212GUI dateGUI) {
        this.dateGUI = dateGUI;
    }

    /**
     * Handles the action when Search is clicked in the GUI.
     *
     * @param event The ActionEvent generated by the user.
     */
    public void actionPerformed(ActionEvent event) {
        String menuName = event.getActionCommand();
        if (menuName.equals("Search")) {
            searchByYear();
        }
    }

    /**
     * Prompts the user to enter a year and displays only dates with that year.
     */
    private void searchByYear() {
        try {
            String yearInput = JOptionPane.showInputDialog(null, "Enter a year:");
            if (yearInput != null) {
                int year = Integer.parseInt(yearInput);
                dateGUI.filterByYear(year);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Invalid input. Please enter a valid year.");
        }
    }
}
