import javax.swing.*;
import java.awt.event.*;
import java.io.*;
import java.util.StringTokenizer;

/**
 * The FileMenuHandler class handles the reading and processing of a file from storage.
 * It implements the ActionListener interface to handle actions when Open or Quit is clicked in the GUI.
 * @author Rodba Khondoker
 */
public class FileMenuHandler implements ActionListener {
    private Date212GUI newdateGUI;

    /**
     * Constructs a FileMenuHandler with a reference to the Date212GUI.
     *
     * @param dateGUI The Date212GUI instance.
     */
    public FileMenuHandler(Date212GUI dateGUI) {
        newdateGUI = dateGUI;
    }

    /**
     * Handles the action when either Open or Quit is clicked in the GUI.
     *
     * @param event The ActionEvent generated by the user.
     */
    @Override
    public void actionPerformed(ActionEvent event) {
        String menuName = event.getActionCommand();
        if (menuName.equals("Open")) {
            openFile();
        } else if (menuName.equals("Quit")) {
            System.exit(0);
        }
    }

    /**
     * Opens files from storage using a file chooser dialog.
     */
    private void openFile() {
    JFileChooser chooser = new JFileChooser();
    int status = chooser.showOpenDialog(null);
    if (status == JFileChooser.APPROVE_OPTION) {
        // Use getAbsolutePath() to get the full path of the selected file
        readSource(chooser.getSelectedFile().getAbsolutePath());
    } else {
        JOptionPane.showMessageDialog(null, "Open File dialog canceled");
    }
}
    /**
     * Reads and processes a text file from storage and adds dates to the lists.
     *
     * @param chosenFile The file to be read.
     */
    private void readSource(String chosenFile) {
        TextFileInput in = new TextFileInput(chosenFile.toString());
        String line = in.readLine();

        while (line != null) {
            StringTokenizer token = new StringTokenizer(line, ",");

            while (token.hasMoreTokens()) {
                // if more tokens exist, continue
                String dateStr = token.nextToken();

                if (dateStr.length() == 8) {
                    try {
                        // Convert String to date Objects
                        Date212 d = new Date212(dateStr);
                        // Add dates to array lists
                        newdateGUI.addToUnsortedList(d);
                        newdateGUI.addToSortedList(d);
                    } catch (IllegalDate212Exception message) {
                        System.out.println(message);
                    }
                }
            }
            
            line = in.readLine();
        }
        populateLists();
    }

    /**
     * Populates the lists in the Date212GUI.
     */
    private void populateLists() {
        newdateGUI.populateLists();
    }
}
